### ISSUE TITLE
Add support for new 'node' API method

### ISSUE THREAD

**Issue by banks** [centrifugal/web#5]
Added in 1.4.0

**Comment by FZambia** [comment]
I thought about this when 1.4.0 out, but have not found a way this command fit into web or API clients. Because it is rather special and returns raw metrics from just one node - we must send request explicitly to that node. In case of web interface request will be sent to one (or maybe random node, but I am planning to get rid of `ActionsHandler` - so it will be always sent to the same node over websocket connection) - is it useful?

**Comment by banks** [comment]
Actually good point. 

I just updated my local single node deploy and saw it wasn't there and filed. But for a real multi-node deployment I'm not sure it does make sense as the UI is now. 

You could have a slightly different UI where the is a second drop down to choose which cluster node to send it too I guess but that's quite a lot of effort for something that's probably not really useful. 

Feel free to close this it's not a real issue I just thought it was an oversight on my part.
